
# BrieFlow configuration file

# Defining samples:
#   Samples must be defined in the following TSV files with columns:
#     sbs_samples.tsv: sample_fp, well, tile, cycle
#     phenotype_samples.tsv: sample_fp, well, tile

# Paths:
#   Paths are resolved relative to the directory the workflow is run from

# Parameters:
aggregate:
  agg_method: median
  aggregate_combo_fp: config/aggregate_combo.tsv
  batch_cols:
  - plate
  - well
  classifier_path: config/naive_mitotic_classifier.pkl
  collapse_cols:
  - sgRNA_0
  - gene_symbol_0
  contamination: 0.01
  control_key: nontargeting
  drop_cols_threshold: 0.1
  drop_rows_threshold: 0.01
  filter_queries: null
  impute: true
  metadata_cols_fp: config/cell_data_metadata_cols.tsv
  perturbation_id_col: sgRNA_0
  perturbation_name_col: gene_symbol_0
  variance_or_ncomp: 0.99
all:
  root_fp: /lab/cheeseman_ops/brieflow-screens/denali-analysis/analysis/analysis_root/
cluster:
  corum_group_benchmark: config/benchmark_clusters/corum_group_benchmark.tsv
  leiden_resolutions:
  - 2
  - 5
  - 10
  min_cell_cutoffs:
    all: 3
    interphase: 3
    mitotic: 0
  string_pair_benchmark: config/benchmark_clusters/string_pair_benchmark.tsv
merge:
  det_range:
  - 0.06
  - 0.065
  initial_sites:
  - - 5
    - 0
  - - 141
    - 32
  - - 370
    - 86
  - - 896
    - 212
  - - 1163
    - 270
  - - 1599
    - 376
  merge_combo_fp: config/merge_combo.tsv
  ph_metadata_channel: null
  sbs_metadata_channel: null
  sbs_metadata_cycle: 1
  score: 0.1
  threshold: 2
phenotype:
  align: false
  cell_diameter: 53.05782348918437
  cellprob_threshold: 0
  channel_names:
  - DAPI
  - COXIV
  - CENPA
  - WGA
  cyto_index: 1
  cyto_model: cyto3
  dapi_index: 0
  flow_threshold: 0.4
  foci_channel: 2
  gpu: false
  mode: null
  nuclei_diameter: 41.97813156768016
preprocess:
  phenotype_channel_order: null
  phenotype_channel_order_flip: null
  phenotype_combo_fp: config/phenotype_combo.tsv
  phenotype_round_order: null
  phenotype_samples_fp: config/phenotype_samples.tsv
  sbs_channel_order: null
  sbs_channel_order_flip: null
  sbs_combo_fp: config/sbs_combo.tsv
  sbs_samples_fp: config/sbs_samples.tsv
sbs:
  alignment_method: DAPI
  bases:
  - G
  - T
  - A
  - C
  cell_diameter: 19.835095646937663
  cellprob_threshold: 0
  cyto_index: 4
  cyto_model: cyto3
  dapi_index: 0
  df_design_path: config/pool10_design.tsv
  flow_threshold: 0.4
  gpu: false
  keep_extras: false
  mode: null
  nuclei_diameter: 9.166995688475083
  q_min: 0
  segmentation_cycle_index: 10
  threshold_peaks: 400
