
# BrieFlow configuration file

# Defining samples:
#   Samples must be defined in the following TSV files with columns:
#     sbs_samples.tsv: sample_fp, well, tile, cycle
#     phenotype_samples.tsv: sample_fp, well, tile

# Paths:
#   Paths are resolved relative to the directory the workflow is run from

# Parameters:
all:
  root_fp: analysis_root/
preprocess:
  phenotype_channel_order: null
  phenotype_channel_order_flip: true
  phenotype_combo_fp: config/phenotype_combo.tsv
  phenotype_round_order: null
  phenotype_samples_fp: config/phenotype_samples.tsv
  sbs_channel_order: null
  sbs_channel_order_flip: true
  sbs_combo_fp: config/sbs_combo.tsv
  sbs_samples_fp: config/sbs_samples.tsv
sbs:
  alignment_method: DAPI
  bases:
  - G
  - T
  - A
  - C
  cell_diameter: 19.802974013476618
  cellpose_model: cyto3
  cellprob_threshold: 0
  cyto_index: 4
  dapi_index: 0
  df_design_path: config/pool10_design.tsv
  flow_threshold: 0.4
  gpu: false
  keep_extras: false
  mode: null
  nuclei_diameter: 9.09728368293446
  q_min: 0
  reconcile: contained_in_cells
  segmentation_cycle_index: 10
  spot_detection_method: spotiflow
  spotiflow_cycle_index: 0
  spotiflow_min_distance: 1
  spotiflow_model: general
  spotiflow_threshold: 0.3
  threshold_peaks: 0
